-- Deprecated migration.
-- Separate customer tester/VIP codes are no longer part of the access model.
-- Use:
--   1. Weekly Guest Code for temporary guest access.
--   2. Approved Member Code for approved members.
--   3. Admin/worker codes for staff access.
--
-- No schema change is needed here. The legacy invite_codes column may remain
-- on older projects for compatibility, but the app no longer exposes it as a
-- separate customer/member access system.
